Sms template fixes
GeorgeKalash/ArgusFE pull request #150
Opened 2024-03-07 07:07 UTC by omarZrayka23

allow delete , allow add newline and null

2024-03-11 12:04 UTC, hadichahine requested changes

2024-03-11 12:04 UTC, hadichahine commented on src/pages/sms-function-templates/index.js
> +return Promise.reject(error);
No need to do that. Remove catch block.

2024-03-11 12:04 UTC, hadichahine commented on src/pages/sms-function-templates/index.js
> +    console.log(initialValues)
Remove.

2024-03-11 12:04 UTC, hadichahine commented on src/pages/sms-function-templates/index.js
> +                   onCellEditStop={value => console.log(value, 'sms')}
What's this? Datagrid shouldn't take this as a prop

2024-03-11 12:04 UTC, hadichahine commented on src/pages/sms-function-templates/index.js
> +                   onChange={value => { console.log(value); formik.setFieldValue('rows', value)}}
Remove log, and rename to something other than rows.

2024-03-11 12:04 UTC, hadichahine commented on src/pages/clients-corporate-list/index.js
>    const [errorMessage, setErrorMessage] = useState(null)
Do we need this?

2024-03-12 11:05 UTC, omarZrayka23 commented on src/pages/clients-corporate-list/index.js
>    const [errorMessage, setErrorMessage] = useState(null)
no

2024-03-13 07:32 UTC, hadichahine requested changes

2024-03-13 07:32 UTC, hadichahine commented on src/components/Shared/DataGrid/components/resourcecombobox/edit.js
> +          newValue
This won't work. Have you tested? Should pass value: value || ''

2024-03-13 07:35 UTC, hadichahine commented on src/pages/clients-corporate-list/index.js
>    const [errorMessage, setErrorMessage] = useState(null)
Remove pls

2024-03-13 07:47 UTC, omarZrayka23 commented on src/pages/clients-corporate-list/index.js
>    const [errorMessage, setErrorMessage] = useState(null)
removed

2024-03-13 08:03 UTC, merged