Rem 202
GeorgeKalash/ArgusFE pull request #183
Opened 2024-04-08 07:13 UTC by RebeccaFrem02

2024-04-16 11:04 UTC, NoraBitarSM commented
functionality tested

2024-04-16 11:27 UTC, Alinadimmokdad commented on src/pages/id-types/index.js
> +    openForm()
spacing

2024-04-23 07:43 UTC, hadichahine requested changes

2024-04-25 05:09 UTC, RebeccaFrem02 commented on src/pages/id-types/forms/IdTypesForm.js
> +            formik && formik.setFieldValue('type', newValue?.key || null)
the formik check is needed but the newValue?.key || null is not, i removed it

2024-04-25 06:48 UTC, hadichahine approved these changes

2024-04-25 06:56 UTC, merged