Product master checkbox
GeorgeKalash/ArgusFE pull request #186
Opened 2024-04-12 06:12 UTC by omarZrayka23

checked and textfield overlap

2024-04-12 07:07 UTC, NoraBitarSM commented
try to switch the added checkbox with a row selection handler

2024-04-15 11:39 UTC, NoraBitarSM commented
functionality tested, approved

2024-04-16 08:21 UTC, hadichahine requested changes

2024-04-16 08:21 UTC, hadichahine commented on src/components/Shared/DataGrid/components/checkbox/edit.js
> +export default function TextFieldEdit({ id, field, value, update, row }) {
Rename to checkbox edit.

2024-04-16 08:21 UTC, hadichahine commented on src/components/Shared/DataGrid/index.js
> +  setSelectRow,
Change this to onSelectionChange.

2024-04-16 08:21 UTC, hadichahine commented on src/components/Shared/DataGrid/index.js
> +  selectedRow,
Why are we passing this?

2024-04-17 08:48 UTC, merged