Rem 237
GeorgeKalash/ArgusFE pull request #205
Opened 2024-04-24 13:23 UTC by Alinadimmokdad

refactoring from CustomComboBox to ResourceComboBox

2024-04-25 11:43 UTC, NoraBitarSM requested changes

2024-05-02 06:06 UTC, omarZrayka23 commented on src/pages/activities/forms/ActivityForm.js
> +      industry: yup.string().required('This field is required')
instead This field is required  put ' '

2024-05-03 06:54 UTC, omarZrayka23 commented on src/pages/mc-defaults/index.js
> +                  formik.setFieldValue('mc_defaultRTFI', newValue?.recordId)
you can replace   formik.setFieldValue('mc_defaultRTFI', newValue?.recordId || '')

2024-05-03 06:54 UTC, omarZrayka23 commented on src/pages/mc-defaults/index.js
> +                  formik.setFieldValue('mc_defaultRTMF', newValue?.recordId)
can do  clear if and put ||

2024-05-03 06:54 UTC, omarZrayka23 commented on src/pages/mc-defaults/index.js
> +                if (newValue) {
can remove if and put ||

2024-05-03 06:54 UTC, omarZrayka23 commented on src/pages/mc-defaults/index.js
> +                if (newValue) {
can remove if and put ||

2024-05-03 06:54 UTC, omarZrayka23 commented on src/pages/rt-default/index.js
>    //stores
clear

2024-05-03 06:54 UTC, omarZrayka23 commented on src/pages/rt-default/index.js
>          rtDefaultValidation.setFieldValue('rt-nra-product', res.record.recordId)
can remove it?

2024-05-03 06:54 UTC, omarZrayka23 commented on src/pages/rt-default/index.js
>    console.log('rtDefaultFormValidation', rtDefaultFormValidation)
remove it

2024-05-06 08:19 UTC, merged