Rem 246
GeorgeKalash/ArgusFE pull request #215
Opened 2024-04-29 06:26 UTC by Alinadimmokdad

chart of account account Ref field

2024-04-29 06:59 UTC, NoraBitarSM commented
the field should be mandatory and should have a label

2024-05-03 04:41 UTC, NoraBitarSM requested changes

2024-05-03 04:41 UTC, NoraBitarSM commented on src/pages/gl-chart-of-accounts/forms/ChartOfAccountsForm.js
> +      activeStatusName: ''
no need for groupName and activeStatusName in the formik instance

2024-05-03 04:41 UTC, NoraBitarSM commented on src/pages/gl-chart-of-accounts/forms/ChartOfAccountsForm.js
>        name: yup.string().required(' '),
status is required also, try to save without status, you will get an error

2024-05-03 04:41 UTC, NoraBitarSM commented on src/pages/gl-chart-of-accounts/forms/ChartOfAccountsForm.js
> +          'Account Reference is incomplete',
no need for this text, it won't be shown anyway

2024-05-03 04:41 UTC, NoraBitarSM commented on src/pages/gl-chart-of-accounts/forms/ChartOfAccountsForm.js
> +      setIsLoading(true)
no need for this

2024-05-03 04:41 UTC, NoraBitarSM commented on src/pages/gl-chart-of-accounts/forms/ChartOfAccountsForm.js
>    const [isLoading, setIsLoading] = useState(false)
no need

2024-05-03 04:41 UTC, NoraBitarSM commented on src/pages/gl-chart-of-accounts/forms/ChartOfAccountsForm.js
> +          toast.error('Failed to fetch record')
?

2024-05-03 04:41 UTC, NoraBitarSM commented on src/pages/gl-chart-of-accounts/forms/ChartOfAccountsForm.js
> +            label='Account Reference'
set the label from labels variable not hardcoded

2024-05-03 04:41 UTC, NoraBitarSM commented on src/pages/gl-chart-of-accounts/index.js
>  import ErrorWindow from 'src/components/Shared/ErrorWindow'
do u need this ?

2024-05-03 04:41 UTC, NoraBitarSM commented on src/pages/gl-chart-of-accounts/index.js
>    const [errorMessage, setErrorMessage] = useState(null)
?

2024-05-03 04:41 UTC, NoraBitarSM commented on src/pages/gl-chart-of-accounts/index.js
>        <ErrorWindow open={errorMessage} onClose={() => setErrorMessage(null)} message={errorMessage} />
?

2024-05-21 07:45 UTC, hadichahine requested changes

2024-05-21 07:45 UTC, hadichahine commented on src/pages/gl-settings/index.js
> +                  label={`Segment Name ${idx + 1}`}
let's move this to labels

2024-05-21 07:45 UTC, hadichahine commented on src/pages/gl-settings/index.js
> +import { useInvalidate, useResourceQuery } from 'src/hooks/resource'
Do w need this?

2024-05-21 07:45 UTC, hadichahine commented on src/pages/gl-chart-of-accounts/index.js
> +    openForm('')
Remove empty strings.

2024-05-21 07:45 UTC, hadichahine commented on src/pages/gl-chart-of-accounts/forms/ChartOfAccountsForm.js
>    const getDataResult = () => {
Rename this to get latest segment data.

2024-05-21 07:45 UTC, hadichahine commented on src/pages/gl-chart-of-accounts/forms/ChartOfAccountsForm.js
> +const SegmentedInput = ({ segments, name, setFieldValue, values, label, error, helperText, required, readOnly }) => {
Place next of Chartofaccountsform. Not nested.

2024-05-21 07:45 UTC, hadichahine commented on src/pages/gl-chart-of-accounts/forms/ChartOfAccountsForm.js
> +      {error && <FormHelperText>{helperText}</FormHelperText>}
Check if need this.

2024-05-27 10:28 UTC, hadichahine approved these changes

2024-05-27 10:31 UTC, merged