Rem 236
GeorgeKalash/ArgusFE pull request #228
Opened 2024-05-08 09:14 UTC by Alinadimmokdad

Sites page

2024-05-08 12:37 UTC, NoraBitarSM commented
functionality tested

2024-05-09 05:20 UTC, omarZrayka23 requested changes

2024-05-09 05:20 UTC, omarZrayka23 commented on src/pages/sites/forms/SitesForm.js
> +      name: yup.string().required(),
work?!    yup.string().required(' '),

2024-05-09 07:02 UTC, Alinadimmokdad commented on src/pages/sites/forms/SitesForm.js
> +      name: yup.string().required(),
done

2024-05-10 13:26 UTC, omarZrayka23 requested changes

2024-05-10 13:26 UTC, omarZrayka23 commented on src/components/Shared/GridToolbar.js
> +          console.error(error)
remove console.log

2024-05-13 05:03 UTC, omarZrayka23 commented on src/pages/cities/Forms/CityForm.js
> +        formik.setValues({
?

2024-05-16 05:41 UTC, merged