Rem 267
GeorgeKalash/ArgusFE pull request #230
Opened 2024-05-09 10:29 UTC by Alinadimmokdad

fi-dimensions

2024-05-15 08:28 UTC, NoraBitarSM commented
functionality tested

2024-05-15 11:09 UTC, Alinadimmokdad commented on src/pages/fi-dimensions/index.js
> +        console.log('obj', myObject)
removed

2024-05-15 11:34 UTC, RebeccaFrem02 commented on src/pages/fi-dimensions/index.js
> +  })
do we need this state?

2024-05-15 11:35 UTC, RebeccaFrem02 commented on src/pages/fi-dimensions/index.js
> +    console.log(dataToPost)
do we need this console?

2024-05-15 11:36 UTC, RebeccaFrem02 commented on src/pages/fi-dimensions/index.js
> +  const handleSubmit = () => {
is there a need to this function? can't we just call formik.handleSubmit() where we need it directly?

2024-05-15 11:37 UTC, RebeccaFrem02 commented on src/pages/fi-dimensions/index.js
> +        <Grid container spacing={3} width={900} sx={{ marginLeft: '0.5rem' }}>
do we need the width and margin here?

2024-05-21 08:21 UTC, hadichahine requested changes

2024-05-21 08:21 UTC, hadichahine commented on src/pages/fi-dimensions/index.js
> +      formik.setFieldValue('DimCount', tempDimCount)
pass event.target.value directly without temp

2024-05-21 08:21 UTC, hadichahine commented on src/pages/fi-dimensions/index.js
> +              onChange={handleDimCountChange}
Remove this

2024-05-21 08:21 UTC, hadichahine commented on src/pages/fi-dimensions/index.js
> +  useEffect(() => {
Move it into onBlur

2024-05-21 08:21 UTC, hadichahine commented on src/pages/fi-dimensions/index.js
> +    const dimCount = formik.values.DimCount
Dim count will be event.target.value

2024-05-21 08:21 UTC, hadichahine commented on src/pages/fi-dimensions/index.js
> +  const handleDimCountChange = event => {
Remove

2024-05-21 08:21 UTC, hadichahine commented on src/pages/fi-dimensions/index.js
> +  const [tempDimCount, setTempDimCount] = useState(null)
Remove

2024-05-21 08:21 UTC, hadichahine commented on src/pages/fi-dimensions/index.js
> +    const myObject = {}
name it as values

2024-05-21 08:21 UTC, hadichahine commented on src/pages/fi-dimensions/index.js
> +    DimCount: null,
Remove

2024-05-24 07:22 UTC, hadichahine approved these changes

2024-05-24 07:38 UTC, merged