Rem 266
GeorgeKalash/ArgusFE pull request #246
Opened 2024-05-21 11:59 UTC by Alinadimmokdad

2024-05-23 10:39 UTC, omarZrayka23 requested changes

2024-05-23 10:39 UTC, omarZrayka23 commented on src/components/Shared/GlobalIntegrationGrid.js
> +  console.log(formik, 'aaaaa')
remove console.log

2024-05-23 10:39 UTC, omarZrayka23 commented on src/pages/fi-tax-codes/forms/HistoryForm.js
> +              height={`${expanded ? height - 280 : 380}px`}
do u need this?

2024-05-23 10:39 UTC, omarZrayka23 commented on src/pages/fi-tax-codes/index.js
> +  const invalidate = useInvalidate({
u can use invalidate in useResourceQuery

2024-05-23 10:39 UTC, omarZrayka23 commented on src/pages/fi-tax-codes/Window/TaxCodesWindow.js
> +  const tabs = [{ label: labels.taxCodes }, { label: labels.history, disabled: !store.recordId }]
name of second tab is hidden ?

2024-05-23 10:39 UTC, omarZrayka23 commented on src/pages/fi-tax-codes/Window/TaxCodesWindow.js
> +          expanded={expanded}
do u need this?

2024-05-23 11:05 UTC, Alinadimmokdad commented on src/components/Shared/GlobalIntegrationGrid.js
> +  console.log(formik, 'aaaaa')
done

2024-05-23 11:05 UTC, Alinadimmokdad commented on src/pages/fi-tax-codes/forms/HistoryForm.js
> +              height={`${expanded ? height - 280 : 380}px`}
no

2024-05-23 11:06 UTC, Alinadimmokdad commented on src/pages/fi-tax-codes/Window/TaxCodesWindow.js
> +          expanded={expanded}
no , removed

2024-05-29 05:55 UTC, hadichahine commented on src/pages/fi-tax-codes/Window/TaxCodesWindow.js
> +  const [editMode, setEditMode] = useState(recordId)
edit mode

2024-05-29 05:55 UTC, hadichahine commented on src/pages/fi-tax-codes/Window/TaxCodesWindow.js
> +          setEditMode={setEditMode}
No need for setEditMode

2024-05-29 05:55 UTC, hadichahine commented on src/pages/fi-tax-codes/forms/HistoryForm.js
> +  const { height } = useWindowDimensions()
Drop all uses of height

2024-05-29 05:55 UTC, hadichahine commented on src/pages/fi-tax-codes/forms/HistoryForm.js
> +          } else {
We already fixed this in the previous commit. Do the same here.

2024-05-29 05:55 UTC, hadichahine commented on src/pages/fi-tax-codes/forms/TaxCodesForm.js
> +  const [editMode, setEditMode] = useState(!!recordId)
Check if we can get this from props.

2024-05-29 05:56 UTC, hadichahine requested changes

2024-05-29 05:56 UTC, hadichahine commented on src/pages/fi-tax-codes/Window/TaxCodesWindow.js
> +  const [editMode, setEditMode] = useState(recordId)
edit mode

2024-05-29 06:57 UTC, hadichahine requested changes

2024-05-29 06:57 UTC, hadichahine commented on src/pages/fi-tax-codes/Window/TaxCodesWindow.js
> +const TaxCodesWindow = ({ height, recordId, labels, maxAccess }) => {
Why do we need height here?

2024-05-29 09:44 UTC, hadichahine approved these changes

2024-05-29 09:55 UTC, merged