Rem 291
GeorgeKalash/ArgusFE pull request #247
Opened 2024-05-21 14:49 UTC by alihajjhassan

2024-05-23 11:18 UTC, RebeccaFrem02 commented on src/pages/pos-users/index.js
> +
remove unused empty lines

2024-05-27 05:20 UTC, FatimaSalami commented
Info button behaviour is not correct: on save it should be enabled.. and on edit mode when clear button is clicked it should be disabled.

2024-06-03 07:23 UTC, hadichahine requested changes

2024-06-03 07:23 UTC, hadichahine commented on src/pages/pos-users/index.js
> +        invalidate: invalidate
Call useINvalidate inside the form.

2024-06-03 07:23 UTC, hadichahine commented on src/pages/pos-users/index.js
> +    invalidate()
refetch or invalidate can work. try refetch

2024-06-03 07:23 UTC, hadichahine commented on src/pages/pos-users/forms/PosUsersForm.js
> +          <Grid container spacing={4}>
Do we need all those grids?

2024-06-03 07:24 UTC, hadichahine requested changes

2024-06-03 07:24 UTC, hadichahine commented on src/pages/pos-users/forms/PosUsersForm.js
> +                    formik.setFieldValue('userId', newValue ? newValue.recordId : '')
newValue?.recordId works too

2024-06-04 06:07 UTC, alihajjhassan commented on src/pages/pos-users/index.js
> +        invalidate: invalidate
i tried doing that but didnt work

2024-06-11 05:09 UTC, merged