Rem 265
GeorgeKalash/ArgusFE pull request #249
Opened 2024-05-22 12:16 UTC by Alinadimmokdad

fi-tax-schedules

2024-05-23 11:35 UTC, RebeccaFrem02 commented on src/pages/fi-tax-schedules/forms/DetailsForm.js
> +    initialValues: {
can we move initial values up?

2024-05-23 11:37 UTC, RebeccaFrem02 commented on src/pages/fi-tax-schedules/forms/DetailsForm.js
> +    <>
is this <> necessary?

2024-05-23 11:37 UTC, RebeccaFrem02 commented on src/pages/fi-tax-schedules/forms/DetailsForm.js
> +              height={`${expanded ? height - 280 : 380}px`}
why are we still sending height here?

2024-05-23 11:38 UTC, RebeccaFrem02 commented on src/pages/fi-tax-schedules/Window/TaxSchedulesWindow.js
> +// ** Custom Imports
this comment serve no purpose

2024-05-28 07:04 UTC, hadichahine requested changes

2024-05-28 07:04 UTC, hadichahine commented on src/pages/fi-tax-schedules/forms/DetailsForm.js
> +  const { height } = useWindowDimensions()
why?

2024-05-28 07:04 UTC, hadichahine commented on src/pages/fi-tax-schedules/forms/DetailsForm.js
> +const DetailsForm = ({ store, setStore, maxAccess, labels, expanded, editMode }) => {
remove unused params

2024-05-28 07:04 UTC, hadichahine commented on src/pages/fi-tax-schedules/forms/DetailsForm.js
> +              id: index + 1,
Why do we need tot do that?

2024-05-28 07:04 UTC, hadichahine commented on src/pages/fi-tax-schedules/forms/DetailsForm.js
> +    recordId &&
if(record)

2024-05-28 07:04 UTC, hadichahine commented on src/pages/fi-tax-schedules/forms/DetailsForm.js
> +            formik.setValues({ TaxDetail: [{ id: 1, taxId: '', taxBase: '', taxCodeId: '', amount: '' }] })
We already have initialvalues I guess.

2024-05-28 07:04 UTC, hadichahine commented on src/pages/fi-tax-schedules/forms/TaxSchedulesForm.js
> +  const [editMode, setEditMode] = useState(!!recordId)
Remove if not needed

2024-05-28 07:19 UTC, Alinadimmokdad commented on src/pages/fi-tax-schedules/Window/TaxSchedulesWindow.js
> +const TaxSchedulesWindow = ({ height, recordId, labels, maxAccess, expanded }) => {
no

2024-05-28 07:21 UTC, Alinadimmokdad commented on src/pages/fi-tax-schedules/forms/DetailsForm.js
> +            formik.setValues({ TaxDetail: [{ id: 1, taxId: '', taxBase: '', taxCodeId: '', amount: '' }] })
yes i am set the Values

2024-05-28 11:01 UTC, hadichahine requested changes

2024-05-28 11:01 UTC, hadichahine commented on src/pages/fi-tax-schedules/forms/TaxSchedulesForm.js
> +  const editMode = !!formik.values.recordId || !!recordId
We're already setting the store recordId. we can stick to !!recordId. I guess editMode is passed from the parent too.

2024-05-28 11:02 UTC, hadichahine requested changes

2024-05-28 11:02 UTC, hadichahine commented on src/pages/fi-tax-schedules/forms/DetailsForm.js
> +  const { height } = useWindowDimensions()
remove

2024-05-28 11:12 UTC, hadichahine approved these changes

2024-05-28 12:21 UTC, merged