add rebuild/ca-rebuild-aba
GeorgeKalash/ArgusFE pull request #260
Opened 2024-05-27 12:59 UTC by Alinadimmokdad

ca-rebuild-aba

2024-05-31 12:52 UTC, omarZrayka23 requested changes

2024-05-31 12:52 UTC, omarZrayka23 commented on src/pages/ca-rebuild-aba/form/CARebuildForm.js
> +                errorCheck={'cashAccountId'}
u do need this

2024-06-11 07:02 UTC, hadichahine requested changes

2024-06-11 07:02 UTC, hadichahine commented on src/pages/ca-rebuild-aba/index.js
> +  }, [_labels, rendered])
Do we need this? Just do _labels

2024-06-11 07:02 UTC, hadichahine commented on src/pages/ca-rebuild-aba/index.js
> +    if (_labels.accountRebuild && !rendered) {
Remove !rendered

2024-06-11 07:02 UTC, hadichahine commented on src/pages/ca-rebuild-aba/index.js
> +  const { labels: _labels, access } = useResourceQuery({
try using useResourceParams

2024-06-11 07:45 UTC, hadichahine approved these changes

2024-06-11 07:47 UTC, merged