Rem 318
GeorgeKalash/ArgusFE pull request #311
Opened 2024-06-24 07:10 UTC by omarZrayka23

After installing and testing agGridReact, everything functions properly on the client side. However, the server side obtains data directly from fetchgridata rather than via a user resource query.

2024-07-03 08:42 UTC, Ghinwa-Arab commented
bugs in:
-checkbox (not binding from API checked data correctly + issues on checking + not submitting the correct chosen rows)
-delete not working (standard & dialog delete)

2024-07-11 06:50 UTC, NoraBitarSM commented
1. open expense type screen, edit any record and open the info button, it will show an error (application error: a client side exception has occured). it works on deploy
![image](https://github.com/GeorgeKalash/ArgusFE/assets/85101826/2282dcec-88f9-4c53-9bf6-1e049bfd09a7)

2. 
![image](https://github.com/GeorgeKalash/ArgusFE/assets/85101826/d0c5c47e-c4eb-4174-b257-72ee1af8f5ac)
can we check all and uncheck all (checkbox not rows) with this feature ? 

3. can we remove this feature for the columns whenever we like to ? or we're stick to it 
![image](https://github.com/GeorgeKalash/ArgusFE/assets/85101826/fae8bb2b-405d-4198-8265-c41dd0b862fc)

4. open currencies screen, it is showing all 186 currencies in one page even though the pagination is saying Displaying Records 1 - 50 Of 186

2024-07-23 07:17 UTC, hadichahine requested changes

2024-07-23 07:17 UTC, hadichahine commented on src/components/Shared/Table.js
> +  fetchGridData,
Remove

2024-07-23 07:17 UTC, hadichahine commented on src/components/Shared/Table.js
> +  handleCheckedRows,
Remove

2024-07-23 07:17 UTC, hadichahine commented on src/components/Shared/Table.js
> +  console.log('columns', columns)
remove

2024-07-23 07:17 UTC, hadichahine commented on src/components/Shared/Table.js
>    const columnsAccess = props.maxAccess && props.maxAccess.record.controls
Make sure this isn't needed

2024-07-26 11:38 UTC, merged