payment-recipe-voucherDefault
GeorgeKalash/ArgusFE pull request #312
Opened 2024-06-24 08:11 UTC by Alinadimmokdad

rv-dtd    /   pv-dtd

2024-06-25 06:20 UTC, Ghinwa-Arab commented
![image](https://github.com/GeorgeKalash/ArgusFE/assets/116278589/b102a015-85ec-4fe7-885f-97fcdf59db89)
 cash lookup not lighting on validation

2024-06-25 06:32 UTC, Ghinwa-Arab commented
![image](https://github.com/GeorgeKalash/ArgusFE/assets/116278589/79983c14-8fd3-4e2b-9e38-cbad2078461e)

in rv doc type defaults cash account lookup not lighting on validation

2024-06-25 06:44 UTC, Ghinwa-Arab commented on src/pages/memos-dtd/[functionId]/form/MemosDtdForm.js
> +import { FormControlLabel, Grid, Checkbox } from '@mui/material'
no need to import FormControlLabel,Checkbox,useState

2024-06-25 06:45 UTC, Ghinwa-Arab commented on src/pages/memos-dtd/[functionId]/form/MemosDtdForm.js
> +      const response = await postRequest({
response not used anywhere remove it and call API directly
await postRequest({
        extension: FinancialRepository.FIDocTypeDefaults.set,
        record: JSON.stringify(obj)
      })

2024-06-25 06:46 UTC, Ghinwa-Arab commented on src/pages/memos-dtd/[functionId]/form/MemosDtdForm.js
> +      toast.success('Record Success')
use plateformLabels

2024-06-25 06:49 UTC, Ghinwa-Arab commented on src/pages/memos-dtd/[functionId]/index.js
> +    toast.success('Record Deleted Successfully')
no hard coded toasts, start using plateformLabels

2024-06-25 06:51 UTC, Ghinwa-Arab commented on src/pages/memos-dtd/[functionId]/index.js
> +  console.log(functionId, 'func index')
remove

2024-06-25 06:51 UTC, Ghinwa-Arab commented on src/pages/pv-dtd/form/PVDocTypeDefaultsForm.js
> +import { useContext, useEffect, useState } from 'react'
no need to import useState

2024-06-25 06:53 UTC, Ghinwa-Arab commented on src/pages/pv-dtd/form/PVDocTypeDefaultsForm.js
> +      const response = await postRequest({
remove const response, call api directly

2024-06-25 06:53 UTC, Ghinwa-Arab commented on src/pages/pv-dtd/form/PVDocTypeDefaultsForm.js
> +      toast.success('Record Success')
use plateform labels

2024-06-25 06:54 UTC, Ghinwa-Arab commented on src/pages/pv-dtd/index.js
> +    toast.success('Record Deleted Successfully')
use plateformLabels

2024-06-25 06:55 UTC, Ghinwa-Arab commented on src/pages/pv-dtd/index.js
> +        dtId: dtId,
enough to pass dtId,

2024-06-25 06:55 UTC, Ghinwa-Arab commented on src/pages/rv-dtd/form/RVDocTypeDefaultsForm.js
> +import { useContext, useEffect, useState } from 'react'
no need to import useState

2024-06-25 06:56 UTC, Ghinwa-Arab commented on src/pages/rv-dtd/form/RVDocTypeDefaultsForm.js
> +      const response = await postRequest({
remove const response

2024-06-25 06:56 UTC, Ghinwa-Arab commented on src/pages/rv-dtd/form/RVDocTypeDefaultsForm.js
> +      toast.success('Record Success')
platformLabels

2024-06-25 06:57 UTC, Ghinwa-Arab commented on src/pages/rv-dtd/index.js
> +    toast.success('Record Deleted Successfully')
plateformLabels

2024-06-25 06:57 UTC, Ghinwa-Arab commented on src/pages/rv-dtd/index.js
> +        dtId: dtId,
dtId, is enough

2024-06-28 07:48 UTC, hadichahine requested changes

2024-06-28 07:48 UTC, hadichahine commented on src/pages/memos-dtd/[functionId]/form/MemosDtdForm.js
> +      formik.setValues({
No need sir. You already have the dtId inside values.

2024-06-28 07:48 UTC, hadichahine commented on src/pages/pv-dtd/form/PVDocTypeDefaultsForm.js
> +      formik.setValues({
We don't need this.

2024-06-28 08:20 UTC, Alinadimmokdad commented on src/pages/rv-dtd/form/RVDocTypeDefaultsForm.js
> +      formik.setValues({
just to give value for recirdId

2024-07-01 05:53 UTC, hadichahine approved these changes

2024-07-01 13:27 UTC, merged