fi-rebuild-aba
GeorgeKalash/ArgusFE pull request #314
Opened 2024-06-24 12:43 UTC by Alinadimmokdad

fi-rebuild-aba

2024-06-25 06:34 UTC, FatimaSalami commented on src/pages/fi-rebuild-aba/form/RebuildAccountBalances.js
> +                  formik && formik.setFieldValue('fiscalYear', newValue?.fiscalYear)
no need to check formik &&

2024-06-25 07:06 UTC, Ghinwa-Arab commented
![image](https://github.com/GeorgeKalash/ArgusFE/assets/116278589/7310ecbd-c6f0-4f1e-b0f1-870032e88e96)

2024-06-25 07:10 UTC, Ghinwa-Arab commented on src/pages/fi-rebuild-aba/form/RebuildAccountBalances.js
> +import { CashBankRepository } from 'src/repositories/CashBankRepository'
no need to import CashBankRepository

2024-06-25 07:11 UTC, Ghinwa-Arab commented on src/pages/fi-rebuild-aba/form/RebuildAccountBalances.js
> +        const response = await postRequest({
remove const response &  call API directly since response not used below

2024-06-25 07:12 UTC, Ghinwa-Arab commented on src/pages/fi-rebuild-aba/form/RebuildAccountBalances.js
> +                    formik.setFieldValue('groupId', newValue?.recordId)
use conditional ternary operator pls

2024-06-26 05:55 UTC, hadichahine requested changes

2024-06-26 05:55 UTC, hadichahine commented on src/pages/fi-rebuild-aba/form/RebuildAccountBalances.js
> +        toast.success('Record Success')
Use platformLabels

2024-06-26 05:55 UTC, hadichahine commented on src/pages/fi-rebuild-aba/form/RebuildAccountBalances.js
> +          ...obj
Is this necessary?

2024-06-26 05:58 UTC, hadichahine requested changes

2024-06-26 05:58 UTC, hadichahine commented on src/pages/fi-rebuild-aba/form/RebuildAccountBalances.js
> +        invalidate()
Can't see an invalidate present!

2024-06-26 06:44 UTC, hadichahine approved these changes

2024-06-26 07:06 UTC, merged