generate opening balances
GeorgeKalash/ArgusFE pull request #315
Opened 2024-06-24 13:44 UTC by Alinadimmokdad

fi-gen-open-bal

2024-06-25 08:11 UTC, RebeccaFrem02 commented on src/pages/fi-gen-open-bal/form/GenerateOpening.js
> +        const { recordId, ...rest } = obj
you may need to use formatDateToApi() check it

2024-06-25 08:11 UTC, RebeccaFrem02 commented on src/pages/fi-gen-open-bal/form/GenerateOpening.js
> +      tbendDate: yup.string().required(' '),
the date is not turning red when submitting it empty

2024-06-26 05:59 UTC, hadichahine requested changes

2024-06-26 05:59 UTC, hadichahine commented on src/pages/fi-gen-open-bal/form/GenerateOpening.js
> +        toast.success('Record Success')
platform labels

2024-06-26 05:59 UTC, hadichahine commented on src/pages/fi-gen-open-bal/form/GenerateOpening.js
> +        invalidate()
where is this declared? I can't see no invalidate. This errors and stays hidden.

2024-06-27 07:50 UTC, hadichahine approved these changes

2024-06-28 06:17 UTC, merged