customDatepickerHijri
GeorgeKalash/ArgusFE pull request #331
Opened 2024-07-03 10:40 UTC by omarZrayka23

i add create customedatepickerHijri component  and import in  individual client and cash invoice

2024-07-04 08:15 UTC, hadichahine requested changes

2024-07-04 08:15 UTC, hadichahine commented on src/pages/clients-list/forms/ClientTemplateForm.js
> +  console.log(clientIndividualFormik)
Remove

2024-07-04 08:15 UTC, hadichahine commented on src/components/Inputs/CustomDatePickerHijri.js
Let's have it take the same props as the normal datepicker, same behavior too.

2024-07-05 08:45 UTC, omarZrayka23 commented on src/pages/currency-trading/forms/TransactionForm.js
> +                          formik.setFieldValue('birth_date', new Date(value)?.getTime() || '')
i  added new Date(value)?.getTime() to convert date to tmestamp cz hijri value read only timestamp

2024-07-05 08:55 UTC, omarZrayka23 commented on src/components/Inputs/CustomDatePickerHijri.js
i do not need all the props why add props not needed

2024-07-05 20:11 UTC, merged