REM-73
GeorgeKalash/ArgusFE pull request #515
Opened 2024-08-22 13:21 UTC by imtithalhalalo

fixing mc-currency-mapping bugs
1- in new mode after save info button should be enable
2- transaction log is empty
3- record id is empty
4- edit any record click “clear” nothing happen

2024-08-26 09:01 UTC, RebeccaFrem02 commented on src/pages/mc-currency-mapping/forms/MultiCurrencyForm.js
> +  const editMode = !!formik.values.recordId || !!recordId
why are we using !!formik.values.recordId?

2024-08-27 06:30 UTC, omarZrayka23 commented on src/pages/mc-currency-mapping/index.js
>  import Table from 'src/components/Shared/Table'
remove  const invalidate = useInvalidate({
    endpointId: MultiCurrencyRepository.McExchangeMap.page
  }).  from index and put invalidate in useResourceQuery

2024-08-27 06:33 UTC, omarZrayka23 commented on src/pages/mc-currency-mapping/index.js
>          invalidate: invalidate
remove invalidate

2024-08-27 06:34 UTC, omarZrayka23 commented on src/pages/mc-currency-mapping/forms/MultiCurrencyForm.js
> +      recordId: recordId || null,
remove || null

2024-08-27 06:35 UTC, omarZrayka23 commented on src/pages/mc-currency-mapping/forms/MultiCurrencyForm.js
> +                  formik && formik.setFieldValue('currencyId', newValue?.recordId || null)
can remove null and put ''

2024-08-27 06:36 UTC, omarZrayka23 commented on src/pages/mc-currency-mapping/forms/MultiCurrencyForm.js
> +                  formik && formik.setFieldValue('rateTypeId', newValue?.recordId || null)
can remove null and put ''

2024-08-27 07:12 UTC, omarZrayka23 commented
<img width="1211" alt="Screenshot 2024-08-27 at 10 11 11 AM" src="https://github.com/user-attachments/assets/ac64008b-3c02-4683-b59c-6b509ffd1fc9">
required and readonly after i write in id

2024-08-27 07:20 UTC, omarZrayka23 requested changes

2024-08-27 07:20 UTC, omarZrayka23 commented on src/pages/mc-currency-mapping/forms/MultiCurrencyForm.js
> +      currencyId: null,
remove  null

2024-08-27 12:40 UTC, Alinadimmokdad commented on src/pages/mc-currency-mapping/forms/MultiCurrencyForm.js
> +      recordId,
recordId : recordId || null

2024-08-27 12:41 UTC, Alinadimmokdad commented on src/pages/mc-currency-mapping/forms/MultiCurrencyForm.js
> +        if (record.rateTypeId && record.currencyId && recordId) {
&& formik.values.recordId ?

2024-08-27 13:23 UTC, merged