REM-563
GeorgeKalash/ArgusFE pull request #619
Opened 2024-10-02 09:08 UTC by RebeccaFrem02

2024-10-02 10:23 UTC, imtithalhalalo commented
![Screenshot 2024-10-02 132228](https://github.com/user-attachments/assets/000ce5fd-2dd9-4490-89b0-b48dd85cb44f)
not showing the name for Employee Ref

2024-10-02 10:26 UTC, imtithalhalalo commented on src/resources/ResourceIds.js
> +  SalesDefaults: 51114,
already exists

2024-10-02 10:27 UTC, imtithalhalalo commented
![Screenshot 2024-10-02 132649](https://github.com/user-attachments/assets/389b8886-fbc8-4f69-b1d6-35990b0dd99a)
it is showing this error in Turnover Rate page

2024-10-02 10:30 UTC, imtithalhalalo commented on src/components/Shared/apiMappings.js
> +    displayField: ['reference', 'name'],
here you added display reference and name but in the columnsInDropdown only name is that how it should be?

2024-10-02 10:30 UTC, imtithalhalalo commented on src/components/Shared/apiMappings.js
> +    displayField: ['reference', 'name'],
also here

2024-10-02 10:31 UTC, imtithalhalalo commented on src/repositories/EmployeeRepository.js
> +    snapshot: service + 'snapshotEM'
this exists on line 5

2024-10-03 10:37 UTC, RebeccaFrem02 commented on src/resources/ResourceIds.js
> +  SalesDefaults: 51114,
where?

2024-10-03 11:26 UTC, imtithalhalalo commented on src/resources/ResourceIds.js
> +  SalesDefaults: 51114,
at the end

2024-10-07 16:43 UTC, NoraBitarSM requested changes
please check for the rest of the HR filters for the fields in dropdown and on selection so the code can stay consistent

2024-10-07 16:43 UTC, NoraBitarSM commented on src/components/Shared/apiMappings.js
> +    columnsInDropDown: [{ key: 'name', value: 'Name' }]
show departmentRef and name in the dropdown and on selection please

2024-10-07 16:43 UTC, NoraBitarSM commented on src/components/Shared/apiMappings.js
> +    columnsInDropDown: [{ key: 'name', value: 'Name' }]
please show positionRef and name in the dropdown and on selection

2024-10-07 16:43 UTC, NoraBitarSM commented on src/components/Shared/apiMappings.js
> +    displayField: ['reference', 'name'],
division doesn't have a reference so you can remove it from the displayField

2024-10-11 10:02 UTC, merged