fix item page
GeorgeKalash/ArgusFE pull request #726
Opened 2024-11-01 11:14 UTC by Alinadimmokdad

fix kit item + priceType
kit item was not enable on submit when kititem checkbox is checked 
price type was not taking a value using default index , because the value that we want to pass to priceType is the key

2024-11-01 11:32 UTC, imtithalhalalo commented
![Screenshot 2024-11-01 133220](https://github.com/user-attachments/assets/42816f2c-7bb4-4652-b9c3-d947ac069f0e)
when adding qty as zero

2024-11-01 11:33 UTC, imtithalhalalo commented
![Screenshot 2024-11-01 133309](https://github.com/user-attachments/assets/c4495210-72de-4b0e-a320-a11ec543b949)
when i don't add rows

2024-11-04 13:35 UTC, imtithalhalalo approved these changes

2024-11-05 06:53 UTC, NoraBitarSM requested changes

2024-11-05 06:53 UTC, NoraBitarSM commented on src/pages/iv-items/forms/ItemsForm.js
> +  async function fetchfirstPriceType() {
refused, we have a defaultIndex for a reason

2024-11-08 08:01 UTC, RebeccaFrem02 commented on src/pages/iv-items/forms/ItemsForm.js
>                      required={!formik.values.kitItem}
remove this leave it just required

2024-11-08 08:05 UTC, RebeccaFrem02 commented on src/pages/iv-items/forms/ItemsForm.js
![image](https://github.com/user-attachments/assets/cebd360a-7af2-41f0-b246-cfc7b0038ed5)


after save and clear the window title shoul be removed

2024-11-08 08:09 UTC, RebeccaFrem02 commented
![image](https://github.com/user-attachments/assets/f8713092-1d83-4e28-ab94-34f5d1f25454)

is currency here mandatory?

2024-11-08 08:11 UTC, RebeccaFrem02 commented
![image](https://github.com/user-attachments/assets/872e4cf1-ec5b-4084-adfa-7c32fad91e79)

after submitting i got a new value in the barcode, check if this is the required behavior

2024-11-08 08:14 UTC, RebeccaFrem02 commented
![image](https://github.com/user-attachments/assets/97bd430e-3286-416b-91f9-2859e041ecfb)

2024-11-08 08:15 UTC, RebeccaFrem02 commented
![image](https://github.com/user-attachments/assets/71638618-9b83-4b9b-92d4-ff93845c7d52)


check if standard cost here is required

2024-11-18 09:43 UTC, RebeccaFrem02 approved these changes

2024-11-18 14:56 UTC, merged