REM-706
GeorgeKalash/ArgusFE pull request #820
Opened 2024-12-03 10:22 UTC by Alinadimmokdad

add 2 new fileds to ct-default : 
ct_min_client_CIVAmount 
ct_default_civ_client

2024-12-05 08:46 UTC, NoraBitarSM requested changes

2024-12-05 08:46 UTC, NoraBitarSM commented on src/pages/ct-default/form/CtDefaults.js
> +                    parameters={{ _category: 1, _size: 30 }}
snapshot doesn't take _size

2024-12-05 08:46 UTC, NoraBitarSM commented on src/pages/ct-default/index.js
> +      height={680}
please decrease the height a little bit and increase the width so the lookup labels are visible

2024-12-05 14:10 UTC, imtithalhalalo commented on src/pages/ct-default/form/CtDefaults.js
> +                      formik && formik.setFieldValue('ct_credit_eval_ratetype_id', newValue?.recordId || null)
is there a need to check for formik?

2024-12-05 14:10 UTC, imtithalhalalo commented on src/pages/ct-default/form/CtDefaults.js
> +      ct_min_client_CIVAmount: '',
why do you have them as empty strings and not null?

2024-12-10 08:23 UTC, imtithalhalalo approved these changes

2024-12-10 08:34 UTC, merged