RM-101
GeorgeKalash/ArgusFE pull request #848
Opened 2024-12-11 14:32 UTC by Alinadimmokdad

new setting page : fo-work-centers

2024-12-12 12:53 UTC, NoraBitarSM requested changes

2024-12-12 12:53 UTC, NoraBitarSM commented on src/resources/DataSets.js
> +  Activity: 190
rename to MF_ACTIVITY

2024-12-12 12:53 UTC, NoraBitarSM commented on src/pages/fo-work-centers/form/WorkCentersForm.js
> +                datasetId={DataSets.Activity}
rename to MF_ACTIVITY

2024-12-12 12:53 UTC, NoraBitarSM commented on src/pages/fo-work-centers/form/WorkCentersForm.js
> +      activity: ''
isn't it better to use null instead of '' ?

2024-12-12 12:53 UTC, NoraBitarSM commented on src/pages/fo-work-centers/form/WorkCentersForm.js
> +                  formik.setFieldValue('activity', newValue?.key || '')
isn't it better to use null instead of '' ?

2024-12-13 13:06 UTC, FatimaSalami commented
on clear reload happened but data don't disappear

2024-12-13 13:09 UTC, FatimaSalami commented on src/pages/fo-work-centers/form/WorkCentersForm.js
> +    enableReinitialize: true,
maybe this can be the reason behind the clear issue but not sure

2024-12-16 08:56 UTC, FatimaSalami approved these changes

2024-12-16 09:21 UTC, NoraBitarSM commented
please show ref and name on selection of the work center

2024-12-16 09:23 UTC, NoraBitarSM requested changes

2024-12-16 09:23 UTC, NoraBitarSM commented on src/components/Shared/FormShell.js
> +                recordId: form.values?.recordId ?? form.values.clientId ?? form.values?.wId,
since when ? 
you set the recordId as wcId in this case

2024-12-16 09:24 UTC, NoraBitarSM requested changes

2024-12-16 09:24 UTC, NoraBitarSM commented on src/pages/fo-work-centers/form/WorkCentersForm.js
> +      workCenterId: null,
why do you have wId and workCenterId ?

2024-12-16 11:25 UTC, merged